version: "3"
services:
   backend:
      build: ./backend
      image: my-backend
      environment:
         DB_HOST: db
         DB_NAME: ${DB_NAME}
         DB_USER: ${DB_USER}
         DB_PASS: ${DB_PASS}
      depends_on:
         db:
            condition: service_healthy

   frontend:
      build: ./frontend
      image: my-frontend
      ports:
         - "8080:80"
      depends_on:
         - backend

   db:
      image: postgres:16
      environment:
         POSTGRES_DB: ${DB_NAME}
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASS}
      volumes:
         - pgdata:/var/lib/postgresql/data
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
         interval: 2s
         timeout: 2s
         retries: 10
volumes:
   pgdata: