version: "3"
services:
  backend:
    image: omerblau/my-backend:latest
    environment:
      DB_HOST: db
      DB_NAME: tasks_db
      DB_USER: tasks_user
      DB_PASS: secret
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: omerblau/my-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasks_user -d tasks_db"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  pgdata:
